### ISSUE TITLE
Errors with  seaborn 0.11.1

### ISSUE THREAD

**Issue by NunoMiranda** [kelvnt/data-drift-detector#1]
Hello

Just to inform
In the `setup.py` of the project, you have `seaborn>=0.11.0`, but with `seaborn 0.11.1` in the environment, some errors occurs.
More precisely:
- `plot_numeric_to_numeric()`  get a warning 
- `plot_categorical_to_numeric()` fails totally

Anyway, nice work on data-drift-detector!
Best regards

**Comment by kelvnt** [comment]
Hey thanks for highlighting this. Just fixed it in the latest version (0.0.3), do check it out and let me know if you still face any issues!
