### ISSUE TITLE
Why must df_prior and df_post have the same lengths? 

### ISSUE THREAD

**Issue by chengyineng38** [kelvnt/data-drift-detector#2]
I was interested in trying this package out, but immediately got an error `ValueError: Lengths must match to compare` because my df_prior and df_post have different lengths. What is the rationale behind the length assertion? If I were to compare data in production vs. new data, the new data would always have more rows than the data in production (since new data = latest data + old production data).

**Comment by kelvnt** [comment]
I am unable to replicate your issue, have just tried it with `df_prior` and `df_post` containing different number of rows and it functions as expected - there is no length assertion being done. You may try the example usage notebook (data-drift-detector/examples/example_usage.ipynb) and change the split to make it uneven and re-run the notebook to test.

Might you have a reproducible example to share? Does any column in your dataset contain a list type?

**Comment by kelvnt** [comment]
Closing issue as no further updates / reproducible example.
