### ISSUE TITLE
Plot categorical - consistent color coding for old and new categorical values

### ISSUE THREAD

**Issue by msank00** [kelvnt/data-drift-detector#3]
Hi Team,

First of all thanks for this great initiative to create such an useful package. 

I am using it for one of our project. However in the drifted data, we have new categorical values and also some old categorical values missing. After applying the data-drift package, facing some color coding consistency issues for old and new categorical levels. 

Can we have something like this.

![image](https://user-images.githubusercontent.com/11691571/120009555-b6d36000-bff9-11eb-90a6-ce67fa141517.png)

- Here I have purposefully kept it `grey` vs `red` when there is a mismatch between categorical values - easy to spot. Also this might be helpful when number of categorical values are more than 10.
- If both dataset has same categorical values, then we can use same color coding and keep the bar position in the same order in both plot.

If you are okay, then I can create a PR for the same.

**Comment by kelvnt** [comment]
Hi,

Sorry for the extremely long delay in responding to this, took a long break on this project of mine. I've made some updates to this package and decided have prior and post categorical plots show up on the same plot so you can compare it side by side, as per the image below. This should be much easier to spot changes in proportions between the prior and post datasets and I think it will fit your uses too. 

![image](https://user-images.githubusercontent.com/26034859/141401697-99cc5b8c-deda-4e96-b3cc-27ad475c0c95.png)
